### ISSUE TITLE
Request for vtk build guide

### ISSUE THREAD

**Issue by adityadua24** [sankhesh/VTKOpenVR#2]
Hi @sankhesh I am working on a university project that requires VR support of vtk.
I have been trying to build vtk including vtkRenderingOpenVR module for several days but I have had no luck. I always get unresolved symbol errors when I try to build the visual studio project.

Could you please share your vtk build binaries of the project or guide me on how to build it ?
It would be a big help

Thanks

**Comment by sankhesh** [comment]
Hi @adityadua24. Sorry for not being able to respond earlier. I am assuming you were able to get past the issue since you closed this.

For VTK issues, I recommend browsing the [VTK mailing lists](http://www.vtk.org/mailing-lists/) and asking questions there for a prompt response.
